version: "3.9"

services:
  db:
    restart: unless-stopped
    image: postgres:11-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
  web:
    build: .
    command: ./docker-entrypoint.sh
    # stdin_open and tty allows to attach and use interactive terminal
    stdin_open: true
    tty: true
    working_dir: /axpo
    volumes:
      - .:/axpo
    ports:
      - "8085:8085"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db